name: CI

on: 
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: setup ros
      run: sudo apt install ros-melodic-desktop -y
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
